export const ERROR = 'ERROR';
export const CREATE_THREAD = 'CREATE_THREAD';
export const CHANGE_THREAD =  'CHANGE_THREAD';
export const REMOVE_THREAD =  'REMOVE_THREAD';
export const UPDATE_THREAD =  'UPDATE_THREAD';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const FORWARD_ATTACHMENT = 'FORWARD_ATTACHMENT';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const RECEIVE_MESSAGE_ACK = 'RECEIVE_MESSAGE_ACK';
export const RECEIVE_MESSAGE_STATUS = 'RECEIVE_MESSAGE_STATUS';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';
export const RECEIVE_IS_TYPING = 'RECEIVE_IS_TYPING';
export const RECEIVE_STOPPED_TYPING = 'RECEIVE_STOPPED_TYPING';
export const MESSAGE_HAS_BEEN_READ = 'MESSAGE_HAS_BEEN_READ';
export const NEW_SCROLL_POSITION = 'NEW_SCROLL_POSITION';
export const UPDATE_JUST_LOGGED_IN = 'UPDATE_JUST_LOGGED_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS';
export const FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE';
export const RECIEVE_THREADS = 'RECIEVE_THREADS';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const PROFILE_CHANGED = 'PROFILE_CHANGED';
export const FETCH_EMR_INTEGRATION = 'FETCH_EMR_INTEGRATION';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_REQUESTS_SUCCESS = 'FETCH_CONTACTS_REQUESTS_SUCCESS';
export const ADD_CONTACTS_REQUESTS = 'ADD_CONTACTS_REQUESTS';
export const REMOVE_CONTACTS_REQUESTS = 'REMOVE_CONTACTS_REQUESTS';
export const SEND_DELIVERED_STATUS = 'SEND_DELIVERED_STATUS';
export const SEND_READ_STATUS = 'SEND_READ_STATUS';
export const FETCHING_PROFILE = 'FETCHING_PROFILE';
export const SEND_ATTACHMENT = 'SEND_ATTACHMENT';
export const FETCH_FLAGS_SUCCESS = 'FETCH_FLAGS_SUCCESS';
export const SAVE_FLAG_SUCCESS = 'SAVE_FLAG_SUCCESS';
export const FETCHING_TOKEN = 'FETCHING_TOKEN';
export const SEND_COMPOSING = 'SEND_COMPOSING';
export const PAUSE_COMPOSING = 'PAUSE_COMPOSING';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_INVITATION = 'CREATE_ROOM_INVITATION';
export const JOIN_ROOM = 'JOIN_ROOM';
export const FETCH_USERS_FOR_ROOM = 'FETCH_USERS_FOR_ROOM';
export const INIT_SOCKET = 'INIT_SOCKET';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAILURE = 'FETCH_ROOMS_FAILURE';
export const RENAME_ROOM = 'RENAME_ROOM';
export const ROOM_JOIN = 'ROOM_JOIN';
export const ROOM_LEAVE = 'ROOM_LEAVE';
export const INVITED_TO_ROOM = 'INVITED_TO_ROOM';
export const FETCH_THREAD_SUCCESS = 'FETCH_THREAD_SUCCESS';
export const FETCH_THREAD_FAILURE = 'FETCH_THREAD_FAILURE';
export const STASH_MESSAGE = 'STASH_MESSAGE';

export const PATIENT = 'PATIENT';
export const STAFF = 'STAFF';

export const RETRY = 'RETRY';
export const SENDING_FAILED = 'SENDING_FAILED';
export const SENDING = 'SENDING';
export const DELIVERED = 'DELIVERED';
export const DISPLAYED = 'DISPLAYED';
export const ACKNOWLEDGED = 'ACKNOWLEDGED';
export const NOTIFIED = 'NOTIFIED';
export const SERVER_ACKNOWLEDGED = 'SERVER_ACKNOWLEDGED';

export const PAGE_SIZE = 25;
export const ONE_MINUTE = 60000;

export const READY = 'READY';

export const NO_SOCKET = 'NO_SOCKET';

export const DISCONNECTED = 'DISCONNECTED';
export const RECONNECTED = 'RECONNECTED';
export const SOCKET_INITIALIZED = 'SOCKET_INITIALIZED';

export const CHECK_UNSENT_MESSAGES = 'CHECK_UNSENT_MESSAGES';
export const RESEND_MESSAGE = 'RESEND_MESSAGE';

export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';

export const ROOM = 'ROOM';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const DELETE_FROM_ROOM = 'DELETE_FROM_ROOM';
export const ADD_NEW_ROOM_QUEUE = 'ADD_NEW_ROOM_QUEUE';
export const REMOVE_NEW_ROOM_QUEUE = 'REMOVE_NEW_ROOM_QUEUE';
export const ONE_TO_ONE = 'ONE_TO_ONE';

export const SET_FEEDBACK = 'SET_FEEDBACK';
export const SET_CONTEXT_MENU = 'SET_CONTEXT_MENU';

export const PING_CURRENT_TIME = 'PING_CURRENT_TIME';

export const RESET_AUDIO_NOTIFICATION = 'RESET_AUDIO_NOTIFICATION';
export const PLAY_AUDIO_NOTIFICATION = 'PLAY_AUDIO_NOTIFICATION';
export const PAUSE_AUDIO_NOTIFICATION = 'PAUSE_AUDIO_NOTIFICATION';

export const UPDATING_WEB_SETTINGS = 'UPDATING_WEB_SETTINGS';
export const WEB_SETTINGS_UPDATED = 'WEB_SETTINGS_UPDATED';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const PERMISSION_GRANTED = 'granted';
export const PERMISSION_DENIED = 'denied';

export const SET_SEARCH = 'SET_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const CONTACT_ACCEPTED = 'CONTACT_ACCEPTED';
export const CONTACT_DECLINED = 'CONTACT_DECLINED';
export const IMAGE_TYPES = [ 'png', 'jpeg', 'jpg', 'gif', 'bmp' ];
export const IMAGE = 'image';
export const OTHER = 'other';

export const SET_SOCKET = 'SET_SOCKET';
export const SET_GROUP_FILTER = 'SET_GROUP_FILTER';

export const REMOVE_TEMP_THREAD = 'REMOVE_TEMP_THREAD';
export const CREATE_TEMP_THREAD = 'CREATE_TEMP_THREAD';

export const IMYD_DATETIME_FORMAT = 'MM/DD/YYYY hh:mm:ss A';
